export const LOGIN_USER = 'LOGIN_USER';
export const SIGNUP_USER = 'SIGNUP_USER';

export const LOGIN_USER_SERVER_RESPONSE_ERROR = 'LOGIN_USER_SERVER_RESPONSE_ERROR';
export const LOGIN_USER_SERVER_RESPONSE_SUCCESS = 'LOGIN_USER_SERVER_RESPONSE_SUCCESS';